### ISSUE TITLE
anonymize.pyがBi.csvを匿名化することにしか対応していない

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#10]
scripts/anonymize/anonymize.py
がコードを書いたときにはBi.csvからCi.csvという大きな匿名化データを作ることだけを想定していたが、最新のルール説明ではsplit.pyでBi.csvを分割した後にBi_0.csv ~ Bi_0.csvを匿名化してCi_0.csv ~ Ci_9.csvを作ることも想定されている。

しかし、現行のコードではBi.csvと異なるサイズのcsvファイルを入力するとassertで弾かれてしまう。このままだと、サンプルコードを使ってもエラーでCi_0を作れない。

split後のBiの入力にも対応させる。

**Comment by gghatano** [comment]
確かに　そうですね

#### 加工関数
random_shuffleは、
・現状：映画の列全体から、ランダムに選んでシャッフル
↓
・更新：データに含まれている映画の列(数値だけの列)からランダムにシャッフルする
としようと思いました

#### チェック部分

・現状
```python
assert Bi.shape == (10000, 51), "invalid Bi"
```
・更新方針
元データB_**.csvと同じ列数・行数であることをチェックするようにします

**Comment by hajimeono96** [comment]
それ以外の部分でもカラム名に関係したエラー吐くことがわかったので、定数でカラム名を参照する処理をBから動的にカラム名を取得するように変更しました

**Comment by gghatano** [comment]
#11  、ありがとうございました

(手元で動作確認します)

ところで
以下２つ、ってどちらかだけでも問題ないですよね（間違っていたらすみません
- anonymize.py
- anonymize_splitted

anoymize.pyに全部を反映して、ルール・運営上問題ないですよね？
@hajimeono96

**Comment by hajimeono96** [comment]
問題ないと思います
