### ISSUE TITLE
MAEの規格化の方法を、ルール資料に合わせる

### ISSUE THREAD

**Issue by gghatano** [pwscup/pwscup2024-dev#12]
右下部黄色枠の箇所。規格化の方法が書いてある。

20000=データに含まれるユーザ数 x 2

クロス集計の誤差の最大値を、人数x2で割るようにする

<img width="922" alt="スクリーンショット 2024-07-24 15 01 17" src="https://github.com/user-attachments/assets/a6a77f44-7a86-47e0-8cde-b2a855bc373f">

[MAEの評価関数](https://github.com/pwscup/pwscup2024-scripts/blob/10-anonymizepy/scripts/evaluate/utilityScore0.py)を更新する

**Comment by gghatano** [comment]
20000で割る、としているので、20000で割るようにしました

**Comment by hajimeono96** [comment]
Mean Absolute Errorという言葉に正確に従うならば10000(行数)な気もしますね。
もしかしたら意味を誤解する参加者が出るかも・・・？

20000で割れば、Bi_j.csvとCi_j.csvの行数が正しければ、必ず値域が0~1になってわかりやすいという利点はあると思います。

**Comment by gghatano** [comment]
マージ済み
