### ISSUE TITLE
スクリプトの使い方や説明のコメント付与とマニュアル作成

### ISSUE THREAD

**Issue by gghatano** [pwscup/pwscup2024-dev#18]
#14 に関連して、各種スクリプトの使い方を追記しておく

参加者向けのスクリプトは、丁寧めに書いておく

**Comment by gghatano** [comment]
#17 とも関連

まずはUsageのメッセージから取り組む

**Comment by hajimeono96** [comment]
このissueは大きすぎるのでいくつかに分割して手分けしてやっつけたいですね

**Comment by gghatano** [comment]
とりあえず一覧
- [ ] 匿名化フェーズ向け
  - [ ] split.py 
  - [ ] anonymize.py
  - [ ] checkCi.py
  - [ ] utilityScore.py
  - [ ] utilityScoreSingle.py
  - [ ] sampleAttack.py
- [ ] 攻撃フェーズ向け  
  - [ ] maketest.py
  - [ ]

**Comment by hajimeono96** [comment]
上のプログラム一覧を確認したところ、sampleAttack.py以外は-hオプションで何が入力で何が出力されるか見れるようになっている印象でした。README.mdにも同様の内容をもう少し詳しく書くようにしましょうか。一旦担当を私にしておきます。
