### ISSUE TITLE
sampleAttack.pyが書き出すE.csvを衝突しにくい名前で書き出すようにする

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#19]
全てE.csvにすると参加者のファイル管理を難しくするかもしれない。
E[攻撃対象チームのid].csvなどが良いと思う。

**Comment by hajimeono96** [comment]
#35 と干渉する可能性があるので保留

**Comment by gghatano** [comment]
E<id>.csvにしましょう！

**Comment by hajimeono96** [comment]
攻撃フェイズ開始前にまた議論するかもしれませんが、一旦closeします
