### ISSUE TITLE
maketest.pyにrandomのシード値を固定する機能を追加

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#20]
シードを固定できる機能もあったほうがdebug等に便利かと思います
コマンドライン引数にオプションで--seedを追加する。オプションを指定しない場合は従来の動作と同じ動作をするようにする。

**Comment by gghatano** [comment]
@hajimeono96  実装してみました！ #29

**Comment by gghatano** [comment]
maketestに関連して、
出力されるs, a, b, xの意味・意図って、ルール資料とか何か別の資料に書いてありますかね？
無ければ、説明を書こうかなと思いました

**Comment by hajimeono96** [comment]
BiaとBibがルール説明用のスライドは「攻撃用データDi」と呼ばれるものに相当するのだろうと検討はつきますが、確かにちゃんとした説明はどこにもない気がします。
