### ISSUE TITLE
sample_anonymize.bashに、サンプル匿名化の結果(サンプル安全性)を表示する

### ISSUE THREAD

**Issue by gghatano** [pwscup/pwscup2024-dev#35]
#34  に関連

maketest.pyとsampleAttack.pyの結果を含めたい　使い方を調査する

**Comment by hajimeono96** [comment]
sampleAttack.pyはコマンドラインへのprintが多く、sample_anonymize.bashみたいなタイプのプログラムの一部として使うとユーザがどこをみていいかわかりにくくなる懸念があります。sampleAttack.py側に最終的な結果以外をprintしないoptionをつける改修もした方がいいかもしれません。

**Comment by gghatano** [comment]
sampleAttack.py の仕様を理解したので、これに取り組みます

適当な攻撃用フォルダを作成し、必要なものをすべて攻撃用フォルダに配置して(ここは諦めた)、sampleAttack.py --id <id> --no_print を実行します

**Comment by gghatano** [comment]
できそう

**Comment by gghatano** [comment]
#40 でレビュー中

**Comment by hajimeono96** [comment]
想定した通りの入力をすればいい感じに動くことを確認したのでdevelopにマージしました。想定していないであろう状態でスクリプトを実行してしまった時にあまり嬉しくない挙動をすることをたまたま発見したので、別のissue立てました。
