### ISSUE TITLE
配布データファイルBの命名規則について

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#39]
配布データ選択についてフォーラムに投稿された記事↓を見て、各プログラムで使っている命名ルールを変更する必要がある可能性に気づきました
https://www.codabench.org/forums/3180/504/

プログラムのコーディングをしていたときにはB98.csvのような名前のデータが配布されると想定していましたが、実際の配布データはBi98.csvという形式でした。(想定していなかったiが入っている)

コードを修正するかどうかは悩みどころですが、忘れないようにここにメモしておきます。

**Comment by gghatano** [comment]
おお...iのところにidが入ると思っていましたね...

**Comment by gghatano** [comment]
BをBi、CをCiにしていくのみですかね

[sample_anonymize.bash](https://github.com/pwscup/pwscup2024-scripts/blob/develop/sample_anonymize.bash) で使っている関数群にて、1つずつやっつけていきます

- [ ] 0 checkhashvalue.py
- [ ] 1. split.py
- [ ] 2. anonymize.py
- [ ] 3. checkCi.py
- [ ] 4. utilityScore.py
- [ ] 5.1 (対象なし) 
- [ ] 5.2 移動対象のファイルの選定
- [ ] 5.3 maketest.py
- [ ] 5.3 sampleAttack.py
- [ ] 6. answerCheck.py

**Comment by hajimeono96** [comment]
codaBenchのHow to anonymizeタブでの説明を読むと当初のB98.csvのような形式であっていたようです。
https://www.codabench.org/competitions/3262/

配布されたデータはBi98.csvのようなiが入った形式なのですが、参加者は配布された3つのデータのうちどれを使うかを選んだら、B30.csv(ここで30はチームid)のように名前を自分で書き換えることとされています。

**Comment by gghatano** [comment]
なるほど

**Comment by gghatano** [comment]
Biが入力されたら/検出したら、B<id>にしてね、とwarningしてあげても良いかもですね
