### ISSUE TITLE
sample_anonymize.bashがdata/inputにBi.csvが配置されていない場合停止するようにする

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#41]
sample_anonymize.bashで指定したidに対応するBi.csvがdata/inputに配置されていなくてもidの値域が正しければ実行しようとしてしまうようです。checkhashvalue.pyでエラーを吐いて、以後同様に全てのPythonコードがエラーを吐きます。

**Comment by gghatano** [comment]
あーなるほどー...確認ありがとうございます

- --idの指定がない場合は、カレントディレクトリを見る
- B<id>のチェック・加工が走るようにする
 
ようにしようと考えていました。

なので、
- カレントディレクトリを見る実装になっていることを確認する
- checkhashvalueが失敗したら止まるようにする

の２点を確認します

**Comment by gghatano** [comment]
set -e として、エラーになったらそこで停止するようにしたので、クローズ
