### ISSUE TITLE
sample_anonymize.bashを任意の匿名化プログラムで実行できるようにする

### ISSUE THREAD

**Issue by hajimeono96** [pwscup/pwscup2024-dev#42]
sample_anonymize.bashはサンプル匿名化プログラムを自動で実行してくれますが、これを任意の匿名化プログラムでも実行できようにしたい。そうすれば、参加者が自分のコードをテストするのが楽になると期待されます。

`bash sample_anonymize.bash --id 98`

が

`bash anonymize.bash --id 98 --script my_anonymize.py`

になるイメージ

**Comment by gghatano** [comment]
my_anonymize、入出力が問題なければ置き換えられるので、

- [ ] 自作匿名化関数を指定するオプションの追加
- [ ] (検討) 入出力の形式が問題ないことの確認 (B<id>_n.csvを入力して C<id>_n.csvを吐くか

上部だけ、とりあえずすぐに対応できそうなので、やっておきます

**Comment by gghatano** [comment]
完了です
